name: qr_pay
description: Scan to pay.

publish_to: "none"
version: 1.0.2

environment:
  sdk: ">=2.18.4 <3.0.0"
dependencies:
  animated_splash_screen: ^1.3.0
  animations: ^2.0.7
  awesome_snackbar_content: ^0.1.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.1.1
  charts_flutter_new: ^0.12.0
  cloud_firestore: ^4.0.4
  cloud_functions: ^4.0.3
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.5
  date_time_picker: ^2.1.0
  dotted_border: ^2.0.0+3
  email_validator: ^2.1.17
  equatable: ^2.0.5
  firebase_admin: ^0.2.0
  firebase_analytics: ^10.1.6
  firebase_app_check: ^0.1.1+8
  firebase_auth: ^4.1.1
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.6
  firebase_dynamic_links: ^5.0.4
  firebase_messaging: ^14.3.0
  firebase_remote_config: ^3.0.4
  firebase_storage: ^11.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_keyboard_visibility: ^5.4.0
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.5
  flutter_svg_provider: ^1.0.3
  fluttertoast: ^8.2.1
  flutterwave_standard: ^1.0.6
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  go_router: ^5.1.1
  google_sign_in: ^5.4.2
  hive: ^2.2.3
  http: ^0.13.5
  image_picker: ^0.8.7
  intl: ^0.17.0
  json_annotation: ^4.7.0
  jwt_decode: ^0.3.1
  localstorage: ^4.0.0+1
  overlay_support: ^2.1.0
  photo_view: ^0.14.0
  provider: ^6.0.5
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0
  responsive_sizer: ^3.1.1
  shared_preferences: ^2.0.16
  step_progress_indicator: ^1.0.2
  syncfusion_flutter_charts: ^21.1.35
  syncfusion_localizations: ^21.1.35
  table_calendar: ^3.0.8
  time_range: ^1.1.0
  url_launcher: ^6.1.7
  uuid: ^3.0.7
  validators: ^3.0.0

dev_dependencies:
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: 6.4.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg_icons/
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
